export const ACTIONS = {
  SEARCH_SONGS: 'SEARCH_SONGS',
  GET_USER: 'GET_USER',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_NEW_RELEASES: ' GET_NEW_RELEASES',
  GET_NEW_RELEASE_TRACKS: 'GET_NEW_RELEASE_TRACKS',
  GET_FEATURED_PLAYLISTS: 'GET_FEATURED_PLAYLISTS',
  GET_PLAYLISTS: 'GET_PLAYLISTS',
  GET_TRACKS: 'GET_TRACKS',
  CLEAR_CONTENT: 'CLEAR_CONTENT',
};
