export const ACTIONS = {
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  ADD_ALBUM: 'ADD_ALBUM',
  SET_USER: 'SET_USER',
  SEARCH_SONGS_SUCCESS: 'SEARCH_SONGS_SUCCESS',
  SEARCH_SONGS_ERROR: 'SEARCH_SONGS_ERROR',
};
